### ISSUE TITLE
Make Pin colors easily ajustible

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#5]
## Usecase
In many thematic maps, the differentiation Initiative/ Company does not make sense. We can hide the Type-Filters in Iframes already, but the pin color remains.

The City of Hahn want to show all sustainable Initiatives and shops in their city, but those, who participate in their local climate-program should get highlighted.

## Solution
Add an additional column `color` in the [categories.csv(https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/Customization#dropdowns) customizabel csv sheet where you can enter an HTML-Code for any colour. 
- If there is a color in the column, than make all pins, which contain one or more tags from the 2nd colum "value" in the corresponding color.
- Fallback-Colors are always the default colors of the map-pins (https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/Customization#pins)
- If the pin corresponds to two different definitions of colors, because it matches with tags from sereval rows in the csv, than use the first value. The color dominances is highest at the top of the list.

----
Similar issue: https://github.com/kartevonmorgen/kartevonmorgen/issues/307
similar to the renn Iframe just not in their CD https://kartevonmorgen.org/renn.html#/?center=50.430,17.271&zoom=6.00&dropdowns=kvm

**Comment by wellemut** [comment]
@navid-kalaei Please start with this issues as soon as possible. 
Do you think this scedule would be manageble?
- [ ] 9.9. 20:00 clickable Prototype
- [ ] 16.9. 20:00 finalized Funktionality, for final testing
- [ ] 23.9. 16:00 ready deployed on production (@alex0107 )

**Comment by wellemut** [comment]
@navid-kalaei please give us an updated schedule of your progress...

**Comment by navid-kalaei** [comment]
## Briefing
the feature is ready to deploy on the test server. please find the documentation on [the wiki page](https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/How-to-customize:-marker-colors). From my side the time is achievable since the feature passed the early tests on the local machine.

## Screenshot
![customized map marker colors based on tags](https://user-images.githubusercontent.com/7106251/190867236-a9167c40-7102-459d-8018-094d7d031859.png)

## TODO

- [ ] @wellemut please inform me or @alex0107 that who would be responsible for deploying on the test server and production

**Comment by wellemut** [comment]
Thank you @navid-kalaei!

 you are responsible to put it on the Testserver/Staging server (it's the same). I think it is https://dev.kartevonmorgen.org/
You should have full access.

If it is running there, I will announce @alex0107 to make it live!

**Comment by navid-kalaei** [comment]
@wellemut i made the dev server online with the latest version of the map. the project is running in a dev mode, which means the tags are not getting synchronized with ofdb continueslly. so if you use a tag, you may not get recommended that again.

Also, as the server is brand-new, some of the first-time configurations stills need to be done. including the CI/CD and GitHub actions. in other words, if you change any files on the github repository it will not get uploaded on the server automatically.

So, for the tasting usecases we can meet online and test together on a call, or if a call is not neccessary just drop in the csv file and i'll upload that to the server manually.

**Comment by wellemut** [comment]
Thank you!
And its already beautifully described: https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/How-to-customize:-marker-colors

**Comment by wellemut** [comment]
Test availiable on https://dev.kartevonmorgen.org/en/m/main?c=48.0063%2C7.8456&z=12.00&search=erneuerbare-energien
![grafik](https://user-images.githubusercontent.com/15019030/191064571-b5c34885-f70a-4e83-8465-fddd8a6a0dfe.png)

**Comment by wellemut** [comment]
Thankyou @navid-kalaei 
Generally it is working exactly as intended!

Just one thing with the csv: if I am using colors like `red` or `yellow` it is working perfectly.
But if I am husing hash codes like #FFDD00 there is a breakdown

https://www.kartevonmorgen.org/m/test?c=50.9792%2C8.7891&z=6.00&search=karte+klimafitkarte
![grafik](https://user-images.githubusercontent.com/15019030/191673467-3b13d4e5-a894-4af9-aed3-fae6a5ccab01.png)

The Console says this
![grafik](https://user-images.githubusercontent.com/15019030/191673635-4aa79182-5220-4483-8369-b32c3c001080.png)

**Comment by wellemut** [comment]
Everything is working perfectly.
Our client ist happy!

**Comment by wellemut** [comment]
German Documentation of this Function: https://blog.vonmorgen.org/pin-farben/

**Comment by navid-kalaei** [comment]
> Thankyou Generally it is working exactly as intended!
> 
> Just one thing with the csv: if I am using colors like `red` or `yellow` it is working perfectly. ~But if I am husing hash codes like #FFDD00 there is a breakdown~
> 
> https://www.kartevonmorgen.org/m/test?c=50.9792%2C8.7891&z=6.00&search=karte+klimafitkarte ![grafik](https://user-images.githubusercontent.com/15019030/191673467-3b13d4e5-a894-4af9-aed3-fae6a5ccab01.png)
> 
> The Console says this ![grafik](https://user-images.githubusercontent.com/15019030/191673635-4aa79182-5220-4483-8369-b32c3c001080.png)

@wellemut the reason is the color should be a valid css parsable. the problems with the values you've introduced are: 1. if they are hex, they should start with `#` sign 2. the letters should be lowercase. please let me know if you still have the problems.

further more you can find more css aliased colors here: https://www.w3schools.com/cssref/css_colors.asp
