### ISSUE TITLE
Desing: Frontend-Finetuning

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#54]
The new frontend is basically done: https://kartevonmorgen.org
There are still some little fuctions needed, but not relevant for desing.
@navid-kalaei has build all functions (its server side rendered)

### Todo
During the Hackathon 2021 we decided, to make the desing look like the old one, as the whole team loves this decent, clear and true desing in black, white and some colours.

- [ ] Copy the old CSS Style to the new frontend @navid-kalaei 

@david-ziegler could you build all the css fintuning:
- [x] Define the correct fonts and font sizes
- [x] use the correct colours of buttons and backgrounds
- [x] add the hover-effects (moving over entries, pins...)
- [x] Add the correct shapes, borders...
- [x] Adding spaces, seperation lines if needed...
- [ ] Check this comment: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/54#issuecomment-1005194854

Thank you very much!

**Comment by wellemut** [comment]
Really beautiful, this new design:
![grafik](https://user-images.githubusercontent.com/15019030/147422237-30fdfe51-f4b4-4701-9e01-98ba6e1b0ef1.png)

compared to the previeous state:
![grafik](https://user-images.githubusercontent.com/15019030/147422249-043ac515-2178-465f-a836-7a1c59c436e7.png)

## Feedback
- can you remove the boarder (or make it white like the background) of the searchbar, especially the horizontal lines.  the vertical lines to seperate the buttons is perfect.
![grafik](https://user-images.githubusercontent.com/15019030/147422285-8f5edc0e-d7ed-4e8d-8c45-20918b0fe2df.png)

- I prefered the little spacing from the top and from the left like in the previous version:
![grafik](https://user-images.githubusercontent.com/15019030/147422292-c55b9743-e488-42cb-a7bb-41c18c413525.png)

- there is still more spacing between the tags than needed:
![grafik](https://user-images.githubusercontent.com/15019030/147422307-9a2e946e-3de2-4413-98cc-edf576f8bba2.png)
- it can be really just a few pixel, like in the old version
![grafik](https://user-images.githubusercontent.com/15019030/147422312-04673cef-d337-44d5-b7e5-0009da051206.png)

**Comment by wellemut** [comment]
## Ratings
- I think we can move the button "rate this entry" to the buttom, below all ratings (just above the footer)
- I really love the design of the ratings from the old version with the horizontal lines and the pins in the corresponding colour
- 
![grafik](https://user-images.githubusercontent.com/15019030/147422395-d91eea60-eab2-4ce4-9178-2bd9c458849a.png)

**Comment by wellemut** [comment]
Really beautiful the new design!

![grafik](https://user-images.githubusercontent.com/15019030/147927058-4633f1c7-772e-420c-a3d8-87738fe45b4c.png)

![grafik](https://user-images.githubuserent.com/15019030/147927094-37503109-7ee7-4a92-8a21-cad4f1d174b5.png)


I love it

@david-ziegler what is your opinion?

**Comment by wellemut** [comment]
@navid-kalaei do you know, why on this new version there is no spacing between symbol and text?

https://kvm-frontend.test.rhw24.it/m/main/e/0e501543f4a84532a6604731582b1fb4?c=50.9630%2C10.7052&z=15.00

![Screenshot_20220103-131823](https://user-images.githubusercontent.com/15019030/147929644-f1009aa0-9504-4f14-a6db-7786a2e98840.png)

**Comment by navid-kalaei** [comment]
add fixed margin between contact icon in the entity detail on commit 74936da

**Comment by wellemut** [comment]
@navid-kalaei 
I have got some more fintunings (i am still in love with the old desing)

- [ ] Remove the spacing above the picture. let it be full size to the top
- [ ] take the picture above the padding-box for the text, so it can be full width of the sidebar
- [ ] Limit the sidebar-width to max-width: 400px; it looks quite stupid, if there is too much white around
- [ ] Make all font-family: "Rubik", sans-serif; 
- [ ] delete the spacing between headline and entry-type
- [ ] Colour of short description, and contact details: rgb(102, 102, 102) (only the adress can be black)
- [ ] Don't forget the three dots ... when shortening the description
- [ ] remove the https:// from the website


![grafik](https://user-images.githubusercontent.com/15019030/148126009-0d20c1df-f972-436f-bab5-6809344ae7a2.png)

**Comment by navid-kalaei** [comment]
@wellemut thank you very much for the precise review, they are tiny changes but huge improvements in the user experience. the question is should move the card to the backlog column as the main visual effects are done or should we transfer the issue back to to-dos.

**Comment by wellemut** [comment]
@navid-kalaei plase invest at least one day to improve the frontend desing and makes it as much to look llike the old frontend.

See also the Todo-Checklist in the issue description and the comments above

**Comment by wellemut** [comment]
New issue, that contains all open todos from this issue with its comments: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/154

I will close this issue and add the new issue to the board instead.
