### ISSUE TITLE
Redirection-Script form old to new URLs

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#94]
## Old Parameters
https://blog.vonmorgen.org/en/iframe/

![old parameters](https://user-images.githubusercontent.com/7106251/154994689-e9edba21-3b43-4607-a86c-f63c9dc1cd74.png)

## New Parameters
- e
- [x] ev Events not working yet
- c
- z
- tag
- search
- sidebar
- [x] orgTag
- [x] fixedTag
- [x] type (category filters are not implemented yet)
- [x] [addentry=initiative](https://kartevonmorgen.org/#/?addentry=initiative)
- [x] make redirection to v0.kartevonmorgen.org
- [x] Define the "map-center" the middle between the right edge of the sidebar and the right edge of the window (so that entries dont get hidden behind the sidebar):  https://github.com/kartevonmorgen/kartevonmorgen/issues/358

**Comment by navid-kalaei** [comment]
done on commit 399830d3e362d50554df98fa8981cd29d2ba274e

**Comment by wellemut** [comment]
Thats perfect!

### Test 1
1. Go to a normal URL https://kartevonmorgen.org/#/?center=50.972,2.373&zoom=5.00&search=Lebensgemeinschaft%20Wandeloase%20%C3%96kodorf%20Ecovillage%20Wohnprojekt%20GemeinschaftinGr%C3%BCndung%20%C3%96kosiedlung&dropdowns=Wandeloasen (or just click http://wandeloasen.vonmorgen.org/)
2. Put dev. in the beginning of the URL like https://dev.kartevonmorgen.org/#/?center=50.972,2.373&zoom=5.00&search=Lebensgemeinschaft Wandeloase Ökodorf Ecovillage Wohnprojekt GemeinschaftinGründung Ökosiedlung&dropdowns=Wandeloasen
3. You get redirected to https://dev.kartevonmorgen.org/m/Wandeloasen?c=50.9720%2C2.3730&z=5.00&search=Lebensgemeinschaft+Wandeloase+%C3%96kodorf+Ecovillage+Wohnprojekt+GemeinschaftinGr%C3%BCndung+%C3%96kosiedlung which is excatly what we want.
✔️

**Comment by wellemut** [comment]
### Test 3
1. Own customized stlyle https://kartevonmorgen.org/renn.html#/?center=49.056,9.382&zoom=7.00&fixedTags=werkzeugkastenwandel
2. With dev. https://dev.kartevonmorgen.org/renn.html#/?center=49.056,9.382&zoom=7.00&fixedTags=werkzeugkastenwandel
3. redirects just back to https://kartevonmorgen.org/renn.html#/?center=49.056,9.382&zoom=7.00&fixedTags=werkzeugkastenwandel same as in Test 2
✔️

**Comment by wellemut** [comment]
### Test 4
1. fixedTag: https://kartevonmorgen.org/#/?center=49.056,9.382&zoom=7.00&fixedTags=werkzeugkastenwandel
2. With dev. https://dev.kartevonmorgen.org/#/?center=49.056,9.382&zoom=7.00&fixedTags=werkzeugkastenwandel
3. redirects to https://dev.kartevonmorgen.org/m/main?c=49.0560%2C9.3820&z=7.00&fixedTags=werkzeugkastenwandel which is a correct translation in the URL, but there is no fixed Tag
❌  failed! fixedTag seems not to be implemented yet

**Comment by wellemut** [comment]
### Test 5
1. orgTag and fixedTag: https://kartevonmorgen.org/#/?center=51.451,6.548&zoom=8.00&fixedTags=eineweltnrw&orgTag=eineweltnrw&dropdowns=ewnnrw
2. with dev https://dev.kartevonmorgen.org/#/?center=51.451,6.548&zoom=8.00&fixedTags=eineweltnrw&orgTag=eineweltnrw&dropdowns=ewnnrw
3. redirects to https://dev.kartevonmorgen.org/m/ewnnrw?c=51.4510%2C6.5480&z=8.00&orgTag=eineweltnrw&fixedTags=eineweltnrw which is basically correct, but not working. 
:x: Filter ist lost! (see Test 4)
:x: controll by orgTag ist lost (see next test)

**Comment by wellemut** [comment]
### Test 6
1. orgTag: https://kartevonmorgen.org/#/?entry=1ac56c70146a46af8431be912d2b586b&center=51.685,12.244&zoom=15.00&orgTag=m4h&dropdowns=kvm
![grafik](https://user-images.githubusercontent.com/15019030/155291603-ddd2a624-ec06-4142-be7b-d667d4aa22df.png)
 (compare this controlled-headline with least unapproved Version without orgTag: https://kartevonmorgen.org/#/?entry=1ac56c70146a46af8431be912d2b586b&center=51.685,12.244&zoom=15.00&dropdowns=kvm
 ![grafik](https://user-images.githubusercontent.com/15019030/155291661-cafdce9e-1337-42a4-a11a-05ff92c31e33.png)
2. with dev: https://dev.kartevonmorgen.org/#/?entry=1ac56c70146a46af8431be912d2b586b&center=51.685,12.244&zoom=15.00&orgTag=m4h&dropdowns=kvm
3. redirects to https://dev.kartevonmorgen.org/m/kvm/e/1ac56c70146a46af8431be912d2b586b?c=51.6850%2C12.2440&z=15.00&orgTag=m4h which is theoretically correct, just the orgTag lost its funcitonality
:x: orgTags not working

- [ ] orgTag functionallity needs to be implemented.

**Comment by wellemut** [comment]
### Test 7 Single Event 
1. Old URL https://kartevonmorgen.org/#/?entry=934654b8e5704405bd1d2210f4ad92dc&center=51.451,6.548&zoom=8.00&dropdowns=ewnnrw
2. with dev. https://dev.kartevonmorgen.org/#/?entry=934654b8e5704405bd1d2210f4ad92dc&center=51.517,7.454&zoom=8.00&dropdowns=ewnnrw
3. redirects to https://dev.kartevonmorgen.org/m/ewnnrw?c=51.5170%2C7.4540&z=8.00 -> the selected entry (event) got completly lost!
:x: Events still fail!

**Comment by wellemut** [comment]
### Test 8 Single Entry 
1. Old URL: https://kartevonmorgen.org/#/?entry=1ac56c70146a46af8431be912d2b586b&center=50.677,11.602&zoom=7.00&dropdowns=kvm
2. with dev: https://dev.kartevonmorgen.org/#/?entry=1ac56c70146a46af8431be912d2b586b&center=50.677,11.602&zoom=7.00&dropdowns=kvm
3. redirects to https://dev.kartevonmorgen.org/m/kvm/e/1ac56c70146a46af8431be912d2b586b?c=50.6770%2C11.6020&z=7.00 which is perfect!
✔️

**Comment by wellemut** [comment]
### Test 9 Hashtag
1. Old URL: https://kartevonmorgen.org/#/?center=50.677,11.602&zoom=7.00&search=%23ideenerfahren17&dropdowns=kvm
2. with dev: https://dev.kartevonmorgen.org/#/?center=50.677,11.602&zoom=7.00&search=%23ideenerfahren17&dropdowns=kvm
3. redirects to https://dev.kartevonmorgen.org/m/kvm?c=50.6770%2C11.6020&z=7.00&tag=ideenerfahren17 which is principally correct, just that the sidebar is wider so that the pins are covered by the sidebar, different than in the old version.
✔️

**Comment by wellemut** [comment]
### Test 10 left=hide
1. Old URL: https://kartevonmorgen.org/#/?center=50.990,6.691&zoom=7.00&search=%23ideenerfahren17&left=hide&dropdowns=kvm
2. with dev.: https://dev.kartevonmorgen.org/#/?center=50.990,6.691&zoom=7.00&search=%23ideenerfahren17&left=hide&dropdowns=kvm
3. redirects to: https://dev.kartevonmorgen.org/m/kvm?c=50.9900%2C6.6910&z=7.00&tag=ideenerfahren17&sidebar=hidden which is principally correct, just that there is a bug in the orientation of the pins
✔️ URL is correct
❌ Pins are wrongly moved to the right:
![grafik](https://user-images.githubusercontent.com/15019030/155293946-f5ee0006-358e-4c77-b6fd-e1fc489bd9f0.png)
This would be correct:
![grafik](https://user-images.githubusercontent.com/15019030/155293843-28eb944a-2863-4330-b8c1-3b1ad68854b3.png)

**Comment by wellemut** [comment]
### Test 11 Filtered categories
1. Old ULR: https://kartevonmorgen.org/#/?center=51.324,9.943&zoom=6.00&categories=event&search=%23poc-regionaltreffen
2. with dev https://dev.kartevonmorgen.org/#/?center=51.324,9.943&zoom=6.00&categories=event&search=%23poc-regionaltreffen
3. redirects to https://dev.kartevonmorgen.org/m/main?c=51.3240%2C9.9430&z=6.00&tag=poc-regionaltreffen which is wrong. 
❌ It should redirect to: https://dev.kartevonmorgen.org/m/main?c=51.8460%2C7.5256&z=7.00&tag=poc-regionaltreffen&type=event (type=event was missing)
❓   Even if I filter only for events. no events are shown! But that seems to be just a problem of the dev.DB because there are no upcoming events in it.

**Comment by wellemut** [comment]
## Test 12 Open Entry Mask
1. Old URL https://kartevonmorgen.org/#/?addentry=initiative
2. with dev https://dev.kartevonmorgen.org/#/?addentry=initiative
3. redirects to https://dev.kartevonmorgen.org/m/main?c=50.8260%2C10.9200&z=7.00 which is wrong
❌ it should redirect to https://dev.kartevonmorgen.org/m/main/e/create but additionally should have selected "Initiative" already
- [ ] implement the create with preselected type...

**Comment by navid-kalaei** [comment]
Thank you very much for your deep careful tests. I'm iterating over the missing parts and here is a briefing:

## Test 2
I changed the redirect URLs to v0.kartevonmorgen.org 01f79f8e6f0495d4b8457e44d12396377c89f933

**Comment by wellemut** [comment]
Allwas show fixed tags as unremovable grey tags in the tagfield 
![grafik](https://user-images.githubusercontent.com/15019030/155883897-fa6f7beb-6f93-4cac-b812-36894039f6df.png)

**Comment by wellemut** [comment]
orgTag funcitonallity will be working on the productive domain.

**Comment by navid-kalaei** [comment]
the "addentry" param is also added. reference #101

**Comment by wellemut** [comment]
- [ ] Adding an entry with type=Event does not yet support predefined tags: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/94#issuecomment-1048621841
- [ ] OrgTags are not supported yet https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/94#issuecomment-1048588496

**Comment by wellemut** [comment]
@alex0107 could you please fix the redirections from old URLs to new ones?
All Mail-Notifications from dev domain contain old urls. Therefore its quite important. 

Example: Nein, Eintrag anschauen oder bearbeiten: https://kartevonmorgen.org/#/?entry=c1686515bb954fd590d2fc995d02fca1

**Comment by alex0107** [comment]
Should work now

**Comment by wellemut** [comment]
The center and zoom in the redirections stopped working!

Thats why all our old City-Links dont work anymore

- https://emmendingen.vonmorgen.org/ becomes https://www.kartevonmorgen.org/m/main?center=48.122%2C7.860&zoom=12.00&c=50.8260%2C10.9200&z=6.00
  - Correct would be `center=48.122%2C7.860&zoom=12.00`
  - but instead it just add  `c=50.8260%2C10.9200&z=6.00`
- http://darmstadt.vonmorgen.org/ becomes https://www.kartevonmorgen.org/m/main?center=49.883%2C8.637&zoom=13.06&c=50.8260%2C10.9200&z=6.00
  - correct would be `center=49.883%2C8.637&zoom=13.06`
  - but it focuses like above just on the default German view: `c=50.8260%2C10.9200&z=6.00`

Obviously the redirection script does not understand the center and zoom of the old urls anymore...
As it was working before, I think it could be linked to the change of the server @alex0107

**Comment by alex0107** [comment]
Maybe I found a bug:
for example if you use this link:
https://dev.kartevonmorgen.org/#/?entry=a3939c8c8ae44f0e81852eb6931657ef&center=47.653,7.913&zoom=9.00&search=wandel/mapAndEntryList.html#/?center=49.815,8.833&zoom=7.0

No makrer is shown

**Comment by wellemut** [comment]
Thats a relly strang URL at the end
>  https://dev.kartevonmorgen.org/#/?entry=a3939c8c8ae44f0e81852eb6931657ef&center=47.653,7.913&zoom=9.00&search=wandel/mapAndEntryList.html#/?center=49.815,8.833&zoom=7.0

your never have such a searchterm: `wandel/mapAndEntryList.html#/?center=49.815,8.833&zoom=7.0` where  did you get this from?

> No makrer is shown
correct

But normally you would use this URL: https://dev.kartevonmorgen.org/m/main/e/a3939c8c8ae44f0e81852eb6931657ef?c=47.6454%2C7.6963&z=16.00

And your original correct URL
> https://dev.kartevonmorgen.org/#/?entry=a3939c8c8ae44f0e81852eb6931657ef&center=47.653,7.913&zoom=9.00&search=wandel
Is perfectly redirecting to https://dev.kartevonmorgen.org/m/main/e/a3939c8c8ae44f0e81852eb6931657ef?c=47.6530%2C7.9130&z=9.00&search=wandel

So technically its all right! Even redirections are working. Perfect!

**Comment by wellemut** [comment]
On the dev domain, all redirections seem to be working (even fixedTags...)
Please bring the latest version to production! @alex0107
